### ISSUE TITLE
True Dark Mode for Time Selector

### ISSUE THREAD

**Issue by octo-kumo** [jfoenixadmin/JFoenix#1103]
Is there a way to implement true dark mode for time selector?
Part of my css
```css
.date-picker-popup > * > * > * > * > * > Circle {
    -fx-fill: rgb(30, 30, 30);
}

.date-picker-popup > * > * > * > * > * > * > * > * > .label {
    -fx-fill: white !important;
    -fx-text-fill: white !important;
}
```

Result:
<img width="241" alt="screenshot" src="https://user-images.githubusercontent.com/26460801/80212254-baafe880-8669-11ea-85d4-2f8c552223a6.png">

What happens is that everything is fine when first opened, but when I drag the hour pointer, the labels turn back to dark text color.
