### ISSUE TITLE
JFXSlider square balloon

### ISSUE THREAD

**Issue by objectProgrammer** [jfoenixadmin/JFoenix#1108]
Is it possible to make the "animated thumb" a square? I tried setting background-insets to 0 but that made it a diamond which isn't what I want.

**Comment by objectProgrammer** [comment]
Solved by using
```css
.jfx-slider .animated-thumb {
	-fx-pref-height: -1;
	-fx-background-radius: 0;
	-fx-rotate: 0;
}

.jfx-slider .animated-thumb > .slider-value {
	-fx-rotate: 0;
}
```
