### ISSUE TITLE
JFXComboBox default styling

### ISSUE THREAD

**Issue by cervonwong** [jfoenixadmin/JFoenix#1146]
I was wondering why the popup listview of JFXComboBox looks like the default ComboBox styling.

![image](https://user-images.githubusercontent.com/44718681/95400266-cf90e780-093c-11eb-9e9a-75e9303353fe.png)

Is there anyway to style the listview to look like the one in material.io, with ripple effect on selection?

Also the popup listview blocks the underline of the JFXComboBox. Is there any way to make it look like this?

![image](https://user-images.githubusercontent.com/44718681/95400374-023ae000-093d-11eb-8a29-c7977a726ef0.png)

**Comment by MarcusOtter** [comment]
Bumping this, I too feel like JFXComboBox leaves a lot to be desired

**Comment by MarcusOtter** [comment]
I experimented a bit and was able to write some css to make the popup appear a few pixels down, so that the underline is shown.
Also, I was able to implement alternating background colors on the items. Change out the colors as you see fit, these are just some random warm-ish colors I used for my application.
```css
.combo-box-popup .list-view {
    -fx-background-color: #e5dbd7;
    -fx-background-radius: 0;
    -fx-translate-y: 2;
}

.combo-box-popup .list-view .list-cell {
    -fx-background-color: #f4eae6;
}

.combo-box-popup .list-view .list-cell:even {
    -fx-background-color: #ede2de;
}
```
