### ISSUE TITLE
How to change the color of the hamburger?

### ISSUE THREAD

**Issue by Seil0** [jfoenixadmin/JFoenix#279]
is there any option to change the color of the three bars of the hamburger-meue icon from black to white?

**Comment by skmedix** [comment]
https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/resources/css/jfoenix-components.css#L12-L17

**Comment by ivanvinski** [comment]
Yes, there is.

`
.jfx-hamburger StackPane {
  -fx-background-color: white;
}
`

**Comment by Seil0** [comment]
I want to change the color of the three bars, not the background. sorry if this was not clear.

**Comment by skmedix** [comment]
But that's how you can change these bars.

---

### Example:
![image](https://cloud.githubusercontent.com/assets/3246162/24420045/b7252a74-13f1-11e7-9cc7-33359fe2a9ae.png)

### Code:
```css
.jfx-hamburger {
	-fx-background-color: lightgrey;
}

.jfx-hamburger StackPane {
	-fx-background-color: green;
}
```
