### ISSUE TITLE
TabPane: Tabs are getting smaller with specific style properties

### ISSUE THREAD

**Issue by skmedix** [jfoenixadmin/JFoenix#332]
**Tested with:**
JFoenix - 1.4.0
JDK - Oracle 1.8.0_131

---

### Result:
![image](https://cloud.githubusercontent.com/assets/3246162/26466888/aa34a278-4190-11e7-975c-0804864f89b1.png)

---

### Style:
```css
.jfx-tab-pane .tab:selected {
    -fx-background-color: #f1f1f1; /* When this */
}

.jfx-tab-pane .tab-label {
    -fx-text-fill: #000;
    -fx-font-weight: normal; /* And this,
                                are both used in style,
                                they're causing this bug */
}
```

### Class:
```java
import com.jfoenix.controls.JFXTabPane;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Tab;
import javafx.stage.Stage;

public class Main extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception{
        JFXTabPane tabPane = new JFXTabPane();
        tabPane.getStylesheets().add(this.getClass().getResource("style.css").toExternalForm());
        for (int i = 0; i <= 4; i++) {
            Tab tab = new Tab();
            tab.setText("Tab " + i);
            tabPane.getTabs().add(tab);
        }
        primaryStage.setScene(new Scene(tabPane, 500, 475));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}

```
