### ISSUE TITLE
JFXTextField CSS v1.7

### ISSUE THREAD

**Issue by rfenters95** [jfoenixadmin/JFoenix#402]
Hello,

I am trying to set the `-jfx-unfocus-color` color value for an JFXTextField in CSS, but when I open the app only the bottom line changes color. However `-jfx-focus-color` also changes the floating label text. While trying to work around this issue, I found that by setting `-fx-prompt-text-fill` from the `.text-field` class and `-fx-background-color` from the `.text-field .input-line` I was able to get the desired unfocused state, but when attempting to change the "unfocused" state at runtime via swapping stylesheets the floating label does not update (as seen in image 4).

main.css
```css
.jfx-text-field
{
    -jfx-focus-color: #4eb769;
    /*-jfx-unfocus-color: #fffd8c; doesn't work*/
}

.text-field
{
    -fx-prompt-text-fill: #fffd8c; /*Yellow - floating label*/
    -fx-text-fill: #fffd8c; /*Yellow - input color*/
    -fx-highlight-fill: #4eb769; /*Green*/
}

.text-field .input-line
{
    -fx-background-color: #fffd8c; /*Yellow - bottom bar*/
}
```

error.css
```css
.jfx-text-field
{
    -jfx-focus-color: red;
}

.text-field
{
    -fx-prompt-text-fill: red;
    -fx-text-fill: red;
}

.text-field .input-line
{
    -fx-background-color: red;
}
```
sample.java
```java
textField.getStylesheets().clear();
textField.getStylesheets().add("error.css");
```

<img width="332" alt="1" src="https://user-images.githubusercontent.com/12780053/29339424-2d12806a-81e8-11e7-996e-80b0a0c61fa1.png">
<img width="331" alt="2" src="https://user-images.githubusercontent.com/12780053/29339423-2d150876-81e8-11e7-8048-73e47d4246c5.png">
<img width="334" alt="3" src="https://user-images.githubusercontent.com/12780053/29339422-2d137ccc-81e8-11e7-8c5c-105b5794ed0e.png">
<img width="331" alt="4" src="https://user-images.githubusercontent.com/12780053/29339425-2d16a104-81e8-11e7-963e-14e776b4af17.png">

**Comment by jfoenixadmin** [comment]
Hello,
can you double check _error.css_ file and make sure it doesn't have some cascading styling regarding the JFXTextField focused color.  as we were not able to reproduce the issue when applying the provided _error.css_ file.

Regards,

**Comment by rfenters95** [comment]
That is the entire _error.css_ file. 

_main.css_ with only (removed all other css in file, for demo)

```css
.jfx-text-field
{
    -jfx-focus-color: #4eb769;
    -jfx-unfocus-color: #fffd8c;
}
```
yields this (unfocused)

<img width="332" alt="1" src="https://user-images.githubusercontent.com/12780053/29367627-8a1168f2-826b-11e7-8285-760cb0ef7610.png">

at runtime I use this java code to change the stylesheet based on whether or not it's value is in a certain range.

```java
textField.getStylesheets().clear();
textField.getStylesheets().add("error.css");
````

_error.css_ with only (removed all other css in file, for demo)
```css
.jfx-text-field
{
    -jfx-focus-color: red;
    -jfx-unfocus-color: red;
}
```
yields this (unfocused)

<img width="333" alt="2" src="https://user-images.githubusercontent.com/12780053/29367997-837bc482-826c-11e7-97ac-f3c5de0be0cc.png">

in the first 4 images I was able to alter the color of the floating label at runtime by changing the `-jfx-focus-color`, however `-jfx-unfocus-color` did not work. The only way I could get it to change while unfocused was to change the `-fx-prompt-text-fill` in the `.text-field` class initially, but once that value was set I was unable to change it.

**Comment by rfenters95** [comment]
**Update: I managed to come up with a work around to my problem.**

All I did was remove jfoenix:1.7.0 and download jfoenix:1.6.0. My CSS files remain the same as they were in my first post.

`-jfx-unfocus-color` property still only changes the color of the line under the input, while `-jfx-focus-color` changes the color of the line under the input and the prompt text.

_main.css_ using maven jfoenix:1.6.0 (only css in file)
```css
.jfx-text-field
{
    -jfx-focus-color: #4eb769;
    -jfx-unfocus-color: #fffd8c;
}
```

Yields the two images below:
1. Unfocused (not typing)
<img width="333" alt="1" src="https://user-images.githubusercontent.com/12780053/29378827-8307d258-828e-11e7-8187-8bd507b9c634.png">

2. Focused (typing)
<img width="328" alt="5" src="https://user-images.githubusercontent.com/12780053/29379202-ae3c5790-828f-11e7-8be6-4e908c4a54a0.png">

_error.css_ using maven jfoenix:1.6.0 (only css in file)
```css
.jfx-text-field
{
    -jfx-focus-color: red;
    -jfx-unfocus-color: red;
}
```

Yields the two images below:
1. Unfocused (not typing)
<img width="329" alt="2" src="https://user-images.githubusercontent.com/12780053/29378833-884d443c-828e-11e7-8f6c-94716bba0c4c.png">

2. Focused (typing)
<img width="328" alt="6" src="https://user-images.githubusercontent.com/12780053/29379237-ce0cb7f4-828f-11e7-88bf-54b962c6e317.png">

However my original files where I set `-fx-prompt-text-fill` in the `.text-field` class and `-fx-background-color` in the `.text-field .input-line` class, now at version 1.6.0, yield the desired result at runtime.

_main.css_ using maven jfoenix:1.6.0 (only css in file)
```css
.jfx-text-field
{
    -jfx-focus-color: #4eb769;
}

.text-field
{
    -fx-prompt-text-fill: #fffd8c; /*Yellow - floating label*/
    -fx-text-fill: #fffd8c; /*Yellow - input color*/
    -fx-highlight-fill: #4eb769; /*Green*/
}

.text-field .input-line
{
    -fx-background-color: #fffd8c; /*Yellow - bottom bar*/
}
```

Yields:

<img width="330" alt="3" src="https://user-images.githubusercontent.com/12780053/29378918-cb430f1a-828e-11e7-9117-0d5b02d9239a.png">


_error.css_ using maven jfoenix:1.6.0 (only css in file)
```css
.jfx-text-field
{
    -jfx-focus-color: red;
}

.text-field
{
    -fx-prompt-text-fill: red;
    -fx-text-fill: red;
}

.text-field .input-line
{
    -fx-background-color: red;
}
```

Yields:

<img width="329" alt="4" src="https://user-images.githubusercontent.com/12780053/29378922-cee103ca-828e-11e7-9333-25092f3329ee.png">
