### ISSUE TITLE
JFXListView Styling doesn't work(?)

### ISSUE THREAD

**Issue by iSach** [jfoenixadmin/JFoenix#411]
Hello, I'm quite new to JavaFX, but I'd like to use your (extremely beautiful) library, thanks a lot for your work on it it's really great!!

I'm having issues with JFXListView, it seems like text fill styling doesn't affect, in a normal ListView it works, but on JFXListView it doesn't, maybe I'm missing something in my css, I don't really know how to use it with JFXListView if it's different from ListView or anything.

Here's my CSS:
https://hastebin.com/tizikazuji.css

ListView result: http://i.isach.be/27_08_2017%4016-57-40.png
JFXListView result: http://i.isach.be/27_08_2017%4016-58-01.png
(with same CSS)

Also, is it possible to change the ripple color? 

Thanks in advance for your help and thanks again for your amazing library!!

**Comment by rfenters95** [comment]
Hello,

I am not the developer, but I think I can help you. Try the code below.

```css
.list-view {
    -fx-background-color: #232323;
}

.list-view .list-cell:hover {
    -fx-background-color: #434343;
}

.list-view .list-cell:selected {
    -fx-background-color: #434343;
}

.list-view .list-cell {
    -fx-background-color: #232323;
    -fx-text-fill: white;
}

.list-view .label {
    -fx-text-fill: white;
}

.jfx-rippler {
    -jfx-rippler-fill: red;
}
```

This produced the following image

JFXListView on the left
ListView on the right

<img width="612" alt="screen shot 2017-08-27 at 5 08 18 pm" src="https://user-images.githubusercontent.com/12780053/29754010-1b0d2caa-8b4b-11e7-8f8c-ecfa30e3454d.png">
