### ISSUE TITLE
JFXProgressBar Styling Bug

### ISSUE THREAD

**Issue by skmedix** [jfoenixadmin/JFoenix#414]
**JFoenix:** 1.7.0
**Java:** Oracle JDK 1.8.0_144

---
**Description:**
1. `-fx-progress-color` doesn't work.
2. Styling .bar or .track in result, coloring whole bar
3. [jfoenix-components.css#L79](https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/resources/css/jfoenix-components.css#L79) is outdated.
---
**ProgressBar set to 0.5**
![image](https://user-images.githubusercontent.com/3246162/29865841-e31191a0-8d76-11e7-96dc-bcdaee84bfe6.png)

**ProgressBar set to -1**
![image](https://user-images.githubusercontent.com/3246162/29865890-0ba03e14-8d77-11e7-81b0-c93d11529ff0.png)

---
**Reproducing:**

Main class:
```java
public class ProgressbarTest extends Application {
	public static void main(String[] args) {
		launch(args);
	}

	@Override
	public void start(Stage primaryStage) throws Exception {
		JFXProgressBar progressBar = new JFXProgressBar();
		progressBar.setProgress(0.5);
		Scene scene = new Scene(progressBar);
		scene.getStylesheets().add(this.getClass().getResource("style.css").toExternalForm());
		primaryStage.setScene(scene);
		primaryStage.show();
	}
}
```

Styling:
```css
.jfx-progress-bar > .track {
    -fx-background-color: red;
}

.jfx-progress-bar > .bar {
    -fx-background-color: blue;
}

.jfx-progress-bar {
    -fx-padding: 10px;
    -fx-progress-color: yellow;
}
```
