### ISSUE TITLE
JFXTreeTableCell/JFXTreeTableColumn Alignment

### ISSUE THREAD

**Issue by TurekBot** [jfoenixadmin/JFoenix#628]
In order to change the [alignment][alignment] of a normal `TreeTableColumn` in a `TreeTableView`, you can [simply do](https://stackoverflow.com/a/29037682/5432315) something like this

    .table-column { //TreeTableColumn's default style class is table-column
        -fx-alignment: center-left;
    }

However, when the same CSS rule is applied to a `TreeTableColumn`s inside a `JFXTreeTableView`, the alignment is all messed up.

Here is a [Short, Self Contained, Correct Example][SSCCE]

bottom-left -> top-left
top-left -> center-left
center-left -> 3/4 up 

It appears to be flipped on its head.

Can this be fixed?

[alignment]: https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#labeled
[SSCCE]: https://github.com/TurekBot/JFXTreeTableView-Column-Alignment-SSCCE

**Comment by TurekBot** [comment]
@jfoenixadmin, I appreciate the work you put into this project.

I tried your solution,

```css
.tree-table-view .tree-table-cell{
    -fx-padding: 0;
    -fx-pref-height: 48px;
}
```
but then we run into the problem of the **expansion node's alignment**, it is always at the top:

![Expansion Node at Top](https://i.imgur.com/PRzSBCv.png)

CSS:
```css
.table-column {
    -fx-alignment: CENTER-LEFT;
}

.tree-table-view .tree-table-cell{
    -fx-padding: 0;
    -fx-pref-height: 48px;
}


```
