### ISSUE TITLE
Customize Tab

### ISSUE THREAD

**Issue by Natreve** [jfoenixadmin/JFoenix#63]
How do you change the color of the tabs selection bar and click animation? from the default yellow?

**Comment by jfoenixadmin** [comment]
you can use the following css selectors : 
<pre>
.jfx-tab-pane .tab-header-area .jfx-rippler{
	-fx-rippler-fill :RED;
}

.jfx-tab-pane .tab-header-area .tab-selected-line{
	-fx-stroke : RED;
}
</pre>

**Comment by Natreve** [comment]
Thanks a lot! that was a big help.

**Comment by Sashie** [comment]
I'm not sure if this is something new or if that was a typo but for anyone wondering why the rippler color wont change in the newer versions, you can use this instead...
```
.jfx-tab-pane .tab-header-area .jfx-rippler{
    -jfx-rippler-fill: RED;
}
```

**Comment by peteralien** [comment]
I'm using the 1.7.0 version of jfoenix, but i can't change the color of the tabs selection bar  :(

Here is the code i'm using:

.jfx-tab-pane
{
  -fx-padding: 1px;
  -fx-background-color: blue, -fx-control-inner-background;
  -fx-background-insets: 0, 1;
}

.jfx-tab-pane .headers-region
{
  -fx-background-color: cornflowerblue;
}

.jfx-tab-pane .tab-header-background
{
  -fx-background-color: cornflowerblue;
}

.jfx-tab-pane .tab-header-area .jfx-rippler
{
  -jfx-rippler-fill: orange;
}

.jfx-tab-pane .tab-header-area .tab-selected-line{
    -fx-stroke: red;
}

Many thanks.

**Comment by jfoenixadmin** [comment]
Hello, 
well JFoenix css properties has been updated, we replaced the prefix "-fx" with "-jfx" to distinguish jfoenix properties from original JavaFX properties.

Regards,

**Comment by Kooldeji** [comment]
For some reason, this doesn't update the selected line's color.

.jfx-tab-pane .tab-selected-line
{
    -fx-stroke: #33ffff;
}

Please, correct this script...

**Comment by skmedix** [comment]
@Kooldeji 
```css
.jfx-tab-pane .tab-selected-line {
    -fx-background-color: #33ffff;
}
```

**Comment by Kooldeji** [comment]
@skmedix
Is it possible to Centralize the tabs on the top bar and also change their text fill. The regular
 `-fx-text-fill: #color;` 
ain't working.

**Comment by skmedix** [comment]
@Kooldeji Yeah, sure
```css
.jfx-tab-pane .tab .tab-label {
    -fx-font-weight: normal;
    -fx-text-fill: #424242;
    -fx-font-size: 16;
}

.jfx-tab-pane .tab:selected .tab-label {
    -fx-text-fill: #000;
}
```
I didn't try tab alignment, but when I'll have more free time I'm gonna check it.
