### ISSUE TITLE
JFXComboBox Text Fill

### ISSUE THREAD

**Issue by pablo67340** [jfoenixadmin/JFoenix#707]
Hey there, so I have a combobox that I have users either typing something in, or selecting from the prebuilt list. Anyways, I am unable to change the text fill color of the box text. I need to make the following text white: 

https://gyazo.com/18454772f1244ad3523b809d4abce12e

I am using the following css: 

.jfx-combo-box {
	-fx-background-color: rgba(0, 0, 0, 0.52);
        -fx-text-fill: WHITE;
}

Any suggestions?

**Comment by myshasis** [comment]
Try this

.combo-box-base .text{
    -fx-fill: white;
}

**Comment by pablo67340** [comment]
Nope, that didnt work either.

**Comment by skmedix** [comment]
```css
.jfx-combo-box {
    -fx-text-inner-color: color;
    -fx-prompt-text-fill: color;
}

.jfx-combo-box .cell {
    -fx-text-fill: color;
}

```
