### ISSUE TITLE
How do I change the foreground color of the tabs on JFXTabPane?

### ISSUE THREAD

**Issue by ivanivamar** [jfoenixadmin/JFoenix#715]
I tried to change it with -fx-text-fill and such either on the SceneBuilder and on the css file but it doesn't do anything. How do I change it?

**Comment by skmedix** [comment]
```css
.jfx-tab-pane .tab-label {
    -fx-text-fill: color;
}
```
