### ISSUE TITLE
Hello, I have questions about TextField!

### ISSUE THREAD

**Issue by buchholz2** [jfoenixadmin/JFoenix#756]
Hi, I'm trying to figure out how to get the bottom line of TextField to get thicker?

![dddd](https://user-images.githubusercontent.com/19735655/41446460-0c293ab0-7026-11e8-9c0c-df6ad4209ab0.png)

**Comment by DropSnorz** [comment]
Hi buch,
Reading [JFXTextFieldSkin.java](https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/skins/JFXTextFieldSkin.java) i've found a quick workaround using CSS.
```css
.jfx-text-field .input-line{
	-fx-pref-height: 3px;
}
.jfx-text-field .input-focused-line{
	-fx-pref-height: 4px;
}
```
![textfield](https://user-images.githubusercontent.com/15964929/41817665-f0fb22ea-779f-11e8-9a3c-30224aa9c45c.png)
