### ISSUE TITLE
JFXComboBox: how to remove underline?

### ISSUE THREAD

**Issue by SeynalKim** [jfoenixadmin/JFoenix#761]

**Comment by DropSnorz** [comment]
I don't know if it's possible to really desactivate the underline. 
It's probably not the proper way to get rid of it, but as discussed in #756, you can still hide the line.

```css
.jfx-combo-box .input-line{
	-fx-pref-height: 0px;
}
.jfx-combo-box .input-focused-line{
	-fx-pref-height: 0px;
}
```
