### ISSUE TITLE
Change JFXCheckBox size 

### ISSUE THREAD

**Issue by goxr3plus** [jfoenixadmin/JFoenix#800]
I can't find out how to do it  , here is an answer for simple CheckBox ( https://stackoverflow.com/questions/39078867/javafx-how-to-resize-a-checkbox )

For a simple JavaFX Check-box this css works great  but for JFXCheckBox not at all : 

```CSS
.medium-check-box > .box {
    -fx-padding: 2em 2em 3em 3em ;
}
.medium-check-box > .box > .mark {
    -fx-padding: 5em 5em 6em 6em; 
}
```
