### ISSUE TITLE
JFXToggleButton radial reaction

### ISSUE THREAD

**Issue by qtran** [jfoenixadmin/JFoenix#874]
Hi,
according to the Material Design guideline the radial reaction isn't needed on desktops app. [https://material.io/design/components/selection-controls.html#switches](url)

How do I hide it? I tried it with CSS but unfortunately without any success.

Regards

**Comment by schlegel11** [comment]
Hi,
if I understand you correctly you don't want to show the rippler circle around the switch right?
You can disable this behaviour via CSS like:

```css
.jfx-toggle-button .jfx-rippler{
    -jfx-rippler-disabled: true;
}
```
Greetings
