### ISSUE TITLE
CSS Styling for JFoenix Autocomplete on ComboBox 

### ISSUE THREAD

**Issue by iCoderJ** [jfoenixadmin/JFoenix#890]
Is there a way to use CSS to style the drop down list background color of the Combo Box? I am using ComboBox (not JFXComboBox) & trying JFoenix Autocompletion, but the CSS styling not working.

I tried with below code as shown in #644 (comment)
.autocomplete-popup .autocomplete-list {
-fx-background-color: yellow;
}

Code used for AutoComplete as shown in https://github.com/jfoenixadmin/JFoenix/issues/220#issuecomment-369017248

Hope the issue faced is clear.

**Comment by schlegel11** [comment]
Hi,
do you want to style the ComboBox or the AutoCompletePopup?
Anyway it doesn't matter because they using the same classes from ListView.
So if you want to change the background color add a CSS file to your scene like:

```java
...
    Scene scene = new Scene(root, 300, 275);
    scene.getStylesheets().add(Main.class.getResource("/main-app.css").toExternalForm());
...
```

In the CSS file you have to define the following:

```css
...
/*Change selected cells of autocomplete popup*/
.jfx-autocomplete-popup .list-cell:filled:selected {
    -fx-background-color: #64ffe6;
}
/*Change cells of autocomplete popup*/
.jfx-autocomplete-popup .list-cell {
    -fx-background-color: #5f68ff;
}
/*Change cells of combobox*/
.combo-box .list-cell {
    -fx-background-color: #ff92b8;
}
...
```
.list-cell has also some other pseudo classes.

That should produce the following:

![peek 2018-12-10 18-05](https://user-images.githubusercontent.com/5841076/49748571-55db3480-fca6-11e8-8d7e-980296961d5d.gif)

Greetings
