### ISSUE TITLE
Cant change the color of the cell inside JFXTreetableView.

### ISSUE THREAD

**Issue by TheSilentHorizon** [jfoenixadmin/JFoenix#918]
When changing the JFXTreeTableViews Selection Mode to cellSelectionEnabled, i cant change the blue of the selected cell with 

```
.tree-table-cell:selected {
   -fx-border-color: green;
}
```

instead it looks like this:

![image](https://user-images.githubusercontent.com/29006783/51253671-4767f300-199f-11e9-8601-c62251d330cc.png)

(its grey because the selected focus is gone. Its actually blue.)

How can i remove this blue background on select?

**Comment by schlegel11** [comment]
Hi,
the solution is the definition of the css property `-fx-selection-bar` in `.tree-table-view`.
There is also a `-fx-selection-bar-non-focused` property.

Like:

```css
...
.tree-table-view {
    -fx-selection-bar: green;
    -fx-selection-bar-non-focused: orange;
}
...
```

![peek 2019-01-20 12-45](https://user-images.githubusercontent.com/5841076/51438825-6624fd00-1cb1-11e9-87f0-125c4e156b4b.gif)

Greetings
